### ISSUE TITLE
Enable searching via transaction hashes

### ISSUE THREAD

**Issue by ipatka** [paradigmxyz/cryo#13]
In addition to block ranges, it would be nice to be able to pull data based on a list of transaction hashes

**Comment by sslivkoff** [comment]
this is on the roadmap

**Comment by ipatka** [comment]
is it in active development? if not would be happy to jump on that

**Comment by sslivkoff** [comment]
here's the current design spec. even though it's a simple feature the implementation might be somewhat involved

transactions are specified using the `--txs <ARGS>` parameter

`<ARGS>` can be one of:
- space-separated list of transaction hashes
- path to parquet file + colon + column name of transactions (e.g. `/path/to/file.parquet:transaction_hash`). can use `transaction_hash` as default column name

the effect of `--txs` will be different for different datatypes:
- for collecting transactions, `--txs` will directly specify which transactions should be collected
- for collecting other datatypes (e.g. datatype "X"), `--txs` will specify collecting all items of type X that are associated with the given transactions
- rpc calls used for collecting each datatype via`--txs`:
    - transactions: eth_getTransactionByHash
    - blocks: eth_getTransactionByHash --> eth_getBlockByNumber
    - logs: eth_getTransactionReceipt.logs
    - traces: trace_transaction
    - state_diffs + vm_traces: trace_replayTransaction

I think the steps for MVP would look something like this:
1. implement `cryo_freeze::Transactions::collect_transaction_chunk()` (stubs for this function already exist in each `Dataset` implementation). this should mirror the `collect_block_chunk()` implementation with a rpc fetcher function and a dataframe converter function
2. implement `--txs` in `cryo_cli::Args.txs` and `cryo_cli::parse_source`. the `cryo_freeze::freeze` function is already able to call `collect_transaction_chunk()` when `Source` contains `TransactionChunk`s instead of `BlockChunk`s

then once that's working can move on to
3. implement `collect_transaction_chunk()` for all of the other `cryo_freeze::Dataset` implementations

for now:
- `--txs` and `--blocks` should be mutually exclusive, only allow combining down the road if there is a clear use case
- do not implement any form of chunking, always output result to single file. in future, could replicate whatever chunking pattern is present in the input. e.g. if given `--txs ethereum__events__*.parquet:transaction_hash`, then produce an output file for each matched input file

before embarking on implementation want to make sure design is rock solid because rust refactors are labor intensive and want to minimize breaking changes to the cli. I think it would be good to try mapping edge cages and obvious future extensions. namely
- what are the scenarios where someone might want to use `--txs`?
- what are weird/pathological edge cases pop up when `--txs` is combined with each other cryo parameters?

based on all of that
- does this functionality cover the use case you had in mind?
- do you see any issues with this design spec?

**Comment by ipatka** [comment]
Main use case I had in mind is for this workflow:

1. Start by block log scanning to get a list of txs I'm interested in investigating further
2. Referencing the tx hashes from step 1, get traces

Also for this flow:

1. Start by block scanning for logs
2. Get subset of txs which also emitted another log

Currently to do this I have to scan all blocks for log type 1, then again for log type 2, then merge the datasets

Spec looks good! Will review carefully before starting dev

**Comment by sslivkoff** [comment]
nice. I need this feature for similar reasons. ideal flow something like

```bash
# this outputs a bunch of ethereum__logs__* files
cryo logs --topic0 <EVENT_HASH> ...

# this outputs a bunch of ethereum__transactions__* files, one for each log file
cryo txs --txs ethereum__logs__* ...

# this outputs a bunch of ethereum__traces__* files, one for each log file
cryo traces --txs ethereum__logs__* ...
```

I think this would cover your use case right?

**Comment by ipatka** [comment]
yup exactly, nice

**Comment by ipatka** [comment]
Added by @sslivkoff in https://github.com/paradigmxyz/cryo/commit/e734f0622105b4bebd21aaebe78bdb7a772aa3d2
