### ISSUE TITLE
Add Accept-Encoding to the request headers to reduce bandwidth usage and improve overall efficiency

### ISSUE THREAD

**Issue by Lucshine** [paradigmxyz/cryo#19]
**Is your feature request related to a problem? Please describe.**
The request header should include {"Accept-Encoding": "gzip"}. As with web3py by default, this option greatly reduces the amount of data transferred in the request, which can easily run out of gigabit bandwidth when connecting to a local LAN node because the transmitted data is uncompressed. Although the use of uncompressed requests can effectively reduce the CPU pressure on the node, whether it is a remote node or a local node, the bandwidth is full and affects the normal operation of the device.

**Describe the solution you'd like**
This feature change could be committed to the ethers-rs project, but I think the need to increase request efficiency is more relevant to this project, so I submit the issue here.

**Comment by sslivkoff** [comment]
this is a good idea. I do think it could only be implemented as part of ethers-rs though, because afaict ether-rs doesn't expose these types of header options to users

ethers-rs is also being refactored into Alloy, so perhaps it would be best to ask for this kind of functionality in the Alloy issue tracker
